- Samples/PSharpFramework/LivenessCheck/App.config
- Samples/PSharpFramework/LivenessCheck/LivenessCheck.csproj
- Samples/PSharpFramework/MultiPaxos/App.config
- Samples/PSharpFramework/MultiPaxos/MultiPaxos.csproj
- Samples/PSharpFramework/PingPong/App.config
- Samples/PSharpFramework/PingPong/PingPong.csproj
PSharp.dll uses Framework v4.6. Upgraded the samples accordingly.
> Upgrade samples to v4.6

- Source/Runtimes/Runtime/Runtime.cs
Patched by @paulthomson -- fixes #21
> Merged the fix about the data race on PSharpRuntime.MachineMap

- Source/Runtimes/BugFindingRuntime/Runtime.cs
Based on the 6889d5b1bc6f2becfeca38c46aec21853fcde127 commit by @paulthomson
> changed the runtime TaskWrapperScheduler field to TaskScheduler

- Source/Core/Tooling/Options/Configuration.cs
- Source/LanguageServices/Compilation/CompilationEngine.cs
> Feature integration: generating pdb files for easier debugging of P# programs

- Libraries/Core/Core.csproj
- Libraries/Core/Exceptions/PSharpException.cs
- Libraries/Core/Exceptions/PSharpIOException.cs
- Libraries/Core/Library/Attributes/Test.cs
- Libraries/Core/Utilities/IO.cs
- Libraries/Core/Utilities/IOLogger.cs
- Libraries/LanguageServices/Compilation/CompilationContext.cs
- Libraries/TestingServices/Engines/AbstractTestingEngine.cs
- Libraries/TestingServices/Engines/BugFindingEngine.cs
- Libraries/TestingServices/Engines/ReplayEngine.cs
- Samples/PSharpAsLanguage/PingPong/Test.cs
I added an option for the user for add their own custom logging routine, as an override of TextWriter. The sample PingPong in "PSharpAsLanguage" folder illustrates the usage. 
I also had to add (optional) TestInit and TestClose methods that are called before and after all the testing iterations, respectively.
> Logging override

- Libraries/LanguageServices/LanguageServices.csproj
- Libraries/LanguageServices/Parsing/Visitors/Identifiers/NameVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/DeferEventsDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/IgnoreEventsDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/StateActionDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Identifiers/NameVisitor.cs
- Libraries/LanguageServices/Rewriting/PSharp/Types/HaltEventRewriter.cs
- Libraries/LanguageServices/Syntax/Declarations/StateDeclaration.cs
- Tests/LanguageServices.Tests.Unit/Declarations/Correct/StateTests.cs
- Tests/LanguageServices.Tests.Unit/Declarations/StaticError/StateFailTests.cs
Fixes #54 and #55.
Also improves the rewriting of "halt" and "default".
> Parsing generic names

- Libraries/Core/Runtime/Runtime.cs
- Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Small, self-explanatory change I think
> Fix #72. SendEvent logs the machine that invoked it.

- Libraries/LanguageServices/LanguageServices.csproj
- Libraries/LanguageServices/Parsing/Parsers/PSharpParser.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/BaseTokenVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/EventDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/MachineDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/MachineMemberDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/MachineMethodDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/StateDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Declarations/StateGroupDeclarationVisitor.cs
- Libraries/LanguageServices/Parsing/Visitors/Syntax/Modifiers/ModifierVisitor.cs
- Libraries/LanguageServices/Rewriting/PSharp/PSharpRewriter.cs
- Libraries/LanguageServices/Syntax/Declarations/EventDeclaration.cs
- Libraries/LanguageServices/Syntax/Declarations/FieldDeclaration.cs
- Libraries/LanguageServices/Syntax/Declarations/MachineDeclaration.cs
- Libraries/LanguageServices/Syntax/Declarations/StateDeclaration.cs
- Libraries/LanguageServices/Syntax/Modifiers/ModifierSet.cs
- Tests/LanguageServices.Tests.Unit/Declarations/Correct/EventTests.cs
- Tests/LanguageServices.Tests.Unit/Declarations/StaticError/EventFailTests.cs
- Tests/LanguageServices.Tests.Unit/Declarations/StaticError/MethodFailTests.cs
- Tests/LanguageServices.Tests.Unit/Declarations/StaticError/StateGroupFailTests.cs
- Tests/LanguageServices.Tests.Unit/LanguageServices.Tests.Unit.csproj
This addresses #129. I also refactored parsing code to increase code reuse. I also added new unit tests (and updated old ones).
> Added support for event declarations in machine scope 

- Libraries/LanguageServices/Parsing/Visitors/Syntax/Types/TypeIdentifierVisitor.cs
- Tests/LanguageServices.Tests.Unit/Declarations/Correct/FieldTests.cs
- Tests/LanguageServices.Tests.Unit/Declarations/Correct/MachineTests.cs
> Parse type identifiers with "[]"

- Libraries/Core/Library/Monitor.cs
- Tests/TestingServices.Tests.Unit/Generics/Correct/GenericMonitorTest.cs
- Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj
To declare generic monitor classes. Simple port of the changes done for supporting generic machines.
> Support for generic monitors

- Libraries/Core/Library/Machine.cs
- Libraries/Core/Runtime/PSharpRuntime.cs
- Libraries/TestingServices/Runtime/BugFindingRuntime.cs
- Tests/TestingServices.Tests.Unit/RuntimeInterface/CreateAndExecuteTest.cs
- Tests/TestingServices.Tests.Unit/RuntimeInterface/ReceivingExternalEventTest.cs
- Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest.cs
- Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj
> Assertions for calling Receive under synchronous execution

- Libraries/Core/Utilities/Tooling/BaseCommandLineOptions.cs
- Tools/Testing/Tester/Testing/TestingProcess.cs
- Tools/Testing/Tester/Utilities/Reporter.cs
- Tools/Testing/Tester/Utilities/TesterCommandLineOptions.cs
> Fix output dir

- Libraries/Core/Runtime/StateMachineRuntime.cs
- Libraries/TestingServices/Runtime/BugFindingRuntime.cs
For both production and bug-finding runtime.
> Log Send to a halted machine

- Libraries/Core/Core.csproj
- Libraries/Core/Library/AbstractMachine.cs
- Libraries/Core/Library/MachineInfo.cs
- Libraries/Core/Runtime/StateMachineRuntime.cs
- Libraries/TestingServices/Liveness/LivenessChecker.cs
- Libraries/TestingServices/Runtime/BugFindingRuntime.cs
- Libraries/TestingServices/Scheduling/AsynchronousTaskScheduler.cs
- Libraries/TestingServices/Scheduling/BugFindingScheduler.cs
- Libraries/TestingServices/Scheduling/ISchedulable.cs
- Libraries/TestingServices/Scheduling/OperationType.cs
- Libraries/TestingServices/Scheduling/SchedulableInfo.cs
- Libraries/TestingServices/SchedulingStrategies/DFS/DFSStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/DelayBounded/DelayBoundingStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Fuzzing/ProbabilisticRandomStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Fuzzing/RandomStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/ISchedulingStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Prioritized/PCTStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Special/ComboStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Special/InteractiveStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Special/MaceMCStrategy.cs
- Libraries/TestingServices/SchedulingStrategies/Special/ReplayStrategy.cs
- Libraries/TestingServices/TestingServices.csproj
The `ISchedulable` implementation of `MachineInfo` is now in the TestingServices project.
> Refactored machine info

- Source/TestingServices/SchedulingStrategies/Liveness/CycleDetectionStrategy.cs
- Source/TestingServices/StateCaching/Fingerprint.cs
- Source/TestingServices/StateCaching/State.cs
- Source/TestingServices/StateCaching/StateCache.cs
Mainly guarded some debug print statements.
> Clean up CycleDetectionStrategy

- Source/Core/Configuration/Configuration.cs
- Source/TestingServices/Engines/AbstractTestingEngine.cs
- Source/TestingServices/SchedulingStrategies/Special/ReplayStrategy.cs
- Tools/Testing/Tester/Utilities/TesterCommandLineOptions.cs
> Replay can be used as a prefix during testing

- Source/Core/Configuration/Configuration.cs
- Source/LanguageServices/Syntax/Declarations/StateDeclaration.cs
- Tests/LanguageServices.Tests.Unit/Declarations/NameofTests.cs
- Tests/LanguageServices.Tests.Unit/LanguageTestUtilities.cs
- Tests/TestingServices.Tests.Unit/Machines/Declarations/NameofTest.cs
- Tools/Compilation/SyntaxRewriter/Program.cs
(i.e. CSharp 5.0) if requested via Configuration.RewriteCSharpVersion; replace nameof with quoted string
> Support MSBuild 12

- Source/Core/Library/Machine.cs
- Tests/Core.Tests.Unit/Features/OnHaltTest.cs
- Tests/TestingServices.Tests.Unit/Features/OnHaltTest.cs
User callback when a machine is about to be halted. Addresses #235
> On halt cleanup

- Source/Core/Runtime/PSharpRuntime.cs
- Source/Core/Runtime/StateMachineRuntime.cs
- Source/TestingServices/Runtime/BugFindingRuntime.cs
@TedHartMS What do you think? This is in response to Peter's email.
> Report implicit operation group in OnSend log

- Source/Core/Library/SingleStateMachine.cs
- Tests/TestingServices.Tests.Unit/Features/SingleStateMachineTest.cs
Added a baseclass representing a simple machine with no state structure. The user just has to override a `ProcessEvent` method to process each incoming event. The idea is to make it easy to code simple machines.
@pdeligia @TedHartMS What do you guys think?
Akash
> Single state machine

- Source/Core/Library/Events/Event.cs
- Source/LanguageServices/Exceptions/ParsingException.cs
- Source/LanguageServices/Parsing/Lexers/PSharpLexer.cs
- Source/LanguageServices/Parsing/Parsers/PSharpParser.cs
- Source/LanguageServices/Parsing/Parsers/TokenParser.cs
- Source/LanguageServices/Parsing/Tokens/TokenType.cs
- Source/LanguageServices/Parsing/Tokens/TokenTypeRegistry.cs
- Source/LanguageServices/Parsing/Visitors/Syntax/Declarations/EventDeclarationVisitor.cs
- Source/LanguageServices/Parsing/Visitors/Syntax/Declarations/MachineDeclarationVisitor.cs
- Source/LanguageServices/Parsing/Visitors/Syntax/Identifiers/NameVisitor.cs
- Source/LanguageServices/Syntax/Declarations/EventDeclaration.cs
- Source/LanguageServices/Syntax/Declarations/EventDeclarations.cs
- Source/LanguageServices/Syntax/Declarations/MachineDeclaration.cs
- Source/LanguageServices/Syntax/Declarations/NamespaceDeclaration.cs
- Tests/LanguageServices.Tests.Unit/Declarations/EventInheritanceTests.cs
- Tests/LanguageServices.Tests.Unit/Declarations/EventTests.cs
- Tests/TestingServices.Tests.Unit/Machines/Declarations/EventInheritanceTest.cs
Also support InnerException on ParsingException for TokenParser
> Support event inheritance in P# syntax

- Source/Core/IO/Logging/StateMachineLogger.cs
break out string formatting as utility functions
> Logging format strings

- Source/LanguageServices/Parsing/Visitors/Syntax/Declarations/MachineDeclarationVisitor.cs
- Source/LanguageServices/Parsing/Visitors/Syntax/Identifiers/NameVisitor.cs
- Source/LanguageServices/Syntax/Declarations/MachineDeclaration.cs
- Tests/LanguageServices.Tests.Unit/Declarations/MachineTests.cs
- Tests/TestingServices.Tests.Unit/Generics/GenericMachineTest.cs
> Machine inheritance syntax

- .gitignore
- Source/Core/Configuration/Configuration.cs
- Source/Core/Library/AbstractMachine.cs
- Source/Core/Library/Attributes/TestAttributes.cs
- Source/TestingServices/Engines/AbstractTestingEngine.cs
- Source/TestingServices/Engines/BugFindingEngine.cs
- Source/TestingServices/Engines/ReplayEngine.cs
- Source/TestingServices/Scheduling/AsynchronousTaskScheduler.cs
- Tools/Testing/Replayer/Utilities/ReplayerCommandLineOptions.cs
- Tools/Testing/Tester/Testing/TestingProcessFactory.cs
- Tools/Testing/Tester/Utilities/TesterCommandLineOptions.cs
> Ability to replace bug-finding runtime with another

- Source/TestingServices/Engines/AbstractTestingEngine.cs
- Source/TestingServices/TestingServices.csproj
> Addresses #339. Tries to load exe.config file when present.

- Tests/Core.Tests.Unit/ExceptionPropagation/OnExceptionTest.cs
- Tests/TestingServices.Tests.Unit/Timers/StartStopTimerTest.cs
Less to no dependence on timing effects.
> Fixed the non-deterministic tests

- Source/Core/Runtime/Machines/Machine.cs
- Tests/TestingServices.Tests.Unit/Features/OnEventDequeueOrHandledTest.cs
- Tests/TestingServices.Tests.Unit/Features/OnProcessingTest.cs
User callbacks for knowing when the processing of a dequeued event begins and ends.
> Event processing callbacks

- Samples/Language/PingPong.CustomLogging/Test.cs
> Fix in language sample

- Source/Core/IO/Logging/MachineLogger.cs
> OnWait logging message. 

- Common/version.props
- Scripts/NuGet/PSharp.nuspec
- Source/Core/Runtime/ProductionRuntime.cs
- Source/TestingServices/Runtime/TestingRuntime.cs
- Tests/TestingServices.Tests.Unit/Monitors/IdempotentRegisterMonitorTest.cs
- Tools/Visualization/TraceViewer/Properties/AssemblyInfo.cs
And also updated version to `1.4.3`.
Fixes #390.
> Made monitor creation per type idempotent

- Source/Core/Runtime/Machines/BaseMachine.cs
- Source/Core/Runtime/Machines/Machine.cs
- Source/TestingServices/Runtime/TestingRuntime.cs
- Tests/TestingServices.Tests.Unit/Features/OnExceptionTest.cs
Added a test and further fixes.
> Addon fix for #402

- Docs/BuildInstructions.md
build.ps1 now lives in Scripts. The instruction is updated accordingly.
> Update instructions to build

- Common/version.props
- Samples/Framework/build.props
- Scripts/NuGet/PSharp.nuspec
- Scripts/run-tests.ps1
- Source/Core/Core.csproj
- Source/Core/Runtime/Machines/Machine.cs
- Source/Core/Runtime/Machines/SingleStateMachine.cs
- Source/SchedulingStrategies/SchedulingStrategies.csproj
- Source/SharedObjects/SharedObjects.csproj
- Source/TestingServices/Engines/AbstractTestingEngine.cs
- Source/TestingServices/TestingServices.csproj
- Tests/Core.Tests/ExceptionPropagation/OnExceptionTest.cs
- Tests/TestingServices.Tests/Features/OnEventDequeueOrHandledTest.cs
- Tools/Testing/CoverageReportMerger/CoverageReportMerger.csproj
- Tools/Testing/Replayer/Replayer.csproj
- Tools/Testing/Tester/Instrumentation/CodeCoverageInstrumentation.cs
- Tools/Testing/Tester/Interfaces/ITestingProcess.cs
- Tools/Testing/Tester/Interfaces/ITestingProcessScheduler.cs
- Tools/Testing/Tester/Interfaces/KnownTypesProvider.cs
- Tools/Testing/Tester/Monitoring/CodeCoverageMonitor.cs
- Tools/Testing/Tester/Program.cs
- Tools/Testing/Tester/Scheduling/TestingProcessScheduler.cs
- Tools/Testing/Tester/Tester.csproj
- Tools/Testing/Tester/Testing/TestingProcess.cs
- Tools/Testing/Tester/Utilities/DependencyGraph.cs
- Tools/Testing/Tester/Utilities/Reporter.cs
- Tools/Visualization/TraceViewer/Properties/AssemblyInfo.cs
Also removed support for net45 and netstandard1.1
> updated version to 1.5.0

- Common/version.props
- Samples/Framework/build.props
- Samples/Language/build.props
- Scripts/NuGet/PSharp.nuspec
- Source/Core/IMachineRuntime.cs
- Source/Core/IO/Logging/DisposingLogger.cs
- Source/Core/IO/Logging/ILogger.cs
- Source/Core/IO/Logging/MachineLogger.cs
- Source/Core/Runtime/MachineRuntime.cs
- Source/Core/Runtime/Machines/AsyncMachine.cs
- Source/Core/Runtime/Machines/Machine.cs
- Source/Core/Runtime/ProductionRuntime.cs
- Source/Core/Runtime/SendOptions.cs
- Source/TestingServices/Runtime/MachineTestingRuntime.cs
- Source/TestingServices/Runtime/Machines/MachineTestKit.cs
- Source/TestingServices/Runtime/SystematicTestingRuntime.cs
- Tests/Core.Tests/Logging/CustomLoggerTest.cs
- Tests/TestingServices.Tests/Machines/EventHandling/ActionsFailTest.cs
- Tests/TestingServices.Tests/Machines/EventHandling/MaxEventInstancesTest.cs
- Tests/TestingServices.Tests/Machines/Features/EventInheritanceTest.cs
- Tests/TestingServices.Tests/Machines/Integration/OneMachineIntegrationTests.cs
- Tests/TestingServices.Tests/Machines/Integration/TwoMachineIntegrationTests.cs
- Tests/TestingServices.Tests/Machines/Transitions/GotoStateMultipleInActionFailTest.cs
- Tests/TestingServices.Tests/Runtime/MustHandleEventTest.cs
- Tools/Benchmarking/PSharpBenchmarkRunner/Tests/Creation/MachineCreationThroughputBenchmark.cs
- Tools/Benchmarking/PSharpBenchmarkRunner/Tests/Messaging/DequeueEventThroughputBenchmark.cs
- Tools/Benchmarking/PSharpBenchmarkRunner/Tests/Messaging/ExchangeEventLatencyBenchmark.cs
- Tools/Benchmarking/PSharpBenchmarkRunner/Tests/Messaging/SendEventThroughputBenchmark.cs
- Tools/Visualization/TraceViewer/Properties/AssemblyInfo.cs
Also exposed `Stop` in the `IMachineRuntime` interface, and bumped version to `1.6.1`.
> Exposed new send event APIs that receive an operation group id

- Source/TestingServices/Statistics/Coverage/ActivityCoverageReporter.cs
- Tests/TestingServices.Tests/Coverage/ActivityCoverageTest.cs
Add information on events that were not covered, in the coverage report
> Coverage report to include uncovered events
