p-org/PSharp

Libraries/Core/Library/Attributes/Test.cs
Libraries/Core/Utilities/IOLogger.cs
Libraries/TestingServices/Engines/AbstractTestingEngine.cs
Libraries/TestingServices/Engines/BugFindingEngine.cs
Libraries/TestingServices/Engines/ReplayEngine.cs

Also fixed a bug in ReplayEngine. The Dispose methods must be called after runtime.Wait.

Added TestIterationDispose method

---

Libraries/TestingServices/Liveness/LivenessChecker.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Libraries/TestingServices/SchedulingStrategies/DFS/DFSStrategy.cs
Libraries/TestingServices/SchedulingStrategies/DelayBounded/DelayBoundingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Fuzzing/ProbabilisticRandomStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Fuzzing/RandomStrategy.cs
Libraries/TestingServices/SchedulingStrategies/ISchedulingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/OperationBounded/OperationBoundingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Prioritized/PCTStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/InteractiveStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/MaceMCStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/ReplayStrategy.cs

Liveness temperature detection is turned off when scheduler
is not fair.

A scheduler declares if it is fair (probabilistically).

---

Libraries/TestingServices/Engines/BugFindingEngine.cs
Libraries/TestingServices/Scheduling/BugFindingScheduler.cs

Currently, a (liveness) bug caught at max-steps doesn't mean max-steps was hit.

report number of times max-steps was hit

---

Libraries/TestingServices/Engines/AbstractTestingEngine.cs
Libraries/TestingServices/Engines/BugFindingEngine.cs
Tools/Testing/Replayer/Program.cs

Simple change, but required calling `Initialize` before the others:
```
this.Initialize();
this.FindEntryPoint();
this.TestInitMethod = FindTestMethod(typeof(TestInit));
this.TestDisposeMethod = FindTestMethod(typeof(TestDispose));
this.TestIterationDisposeMethod = FindTestMethod(typeof(TestIterationDispose));           
```
Seems fine to me.

Preserve the /method flag in the schedule file

---

Libraries/Core/Library/Machine.cs
Libraries/Core/Library/Monitor.cs
Libraries/Core/Runtime/Runtime.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs

This was a request from Nar. The coverage report was using state names with qualifying the state groups, which can lead to ambiguity. I have fixed this. No tests because it is only for the coverage report. 
I think our logging (of send, etc) should also include qualified names.

Logging should qualify state names with the state groups.

---

Libraries/Core/Library/Machine.cs
Tests/TestingServices.Tests.Unit/Integration/DynamicError/Advanced/SendInterleavingsTest.cs

Stop the machines from using the state-information cache until it is populated. The fix still ensures that once machine information is cached, no extra synchronization is required.

Concurrent machine creation fix

---

Libraries/TestingServices/Engines/BugFindingEngine.cs
Tools/Testing/Tester/Program.cs
Tools/Testing/Tester/Testing/TestingPortfolio.cs
Tools/Testing/Tester/Testing/TestingProcess.cs
Tools/Testing/Tester/Testing/TestingProcessFactory.cs
Tools/Testing/Tester/Testing/TestingProcessScheduler.cs
Tools/Testing/Tester/Utilities/TesterCommandLineOptions.cs

Hi Pantazis,
We should make `PSharpTester` (optionally) deterministic so that different people can execute it and get the exact same result. You already had the seed option. I just made sure that parallel testing tasks don't get the exact same seed (because they will then do the same thing). I also print the seed if its not supplied.
On the same machine, I get the exact same behavior once I fix the seed. But not across machines. This may be because the DLLs are different, but I don't see why that should affect the tester. For example, can you try to repro the following and see what you get:
```
C:\Users\akashl\Documents\work\PSharp\Samples\PSharpAsLibrary>..\..\Binaries\PSharpTester.exe /test:Binaries\Debug\Raft.dll /i:10 /parallel:2 /max-steps:100 /sch-seed:620
. Testing …
```

Tester is deterministic, given a seed

---

Tools/Testing/Tester/Testing/TestingProcess.cs

Non-Zero error code, when the PSharpTester finds a bug.
This can be used in batch testing in Azure to cancel all the other test jobs if we find a bug in one of the runs.

Non-Zero exit code when bugs are found

---

Libraries/Core/Library/MachineId.cs
Libraries/Core/Runtime/Runtime.cs
Libraries/TestingServices/SchedulingStrategies/DFS/DFSStrategy.cs
Libraries/TestingServices/Tracing/Machines/MachineActionInfo.cs
Libraries/TestingServices/Tracing/Schedules/ScheduleTrace.cs

Watches for the overflow and asserts false to stop the runtime.

Watch for MachineId counter overflow. Fixes #123

---

Libraries/Core/Core.csproj
Libraries/Core/Library/Machine.cs
Libraries/Core/Library/Monitor.cs
Libraries/Core/Runtime/Exceptions/ExecutionCanceledException.cs
Libraries/Core/Runtime/Exceptions/LoggingException.cs
Libraries/Core/Runtime/Exceptions/RuntimeException.cs
Libraries/Core/Utilities/IO.cs
Libraries/LanguageServices/Compilation/CompilationContext.cs
Libraries/StaticAnalysis/StaticAnalysisEngine.cs
Libraries/TestingServices/Scheduling/BugFindingScheduler.cs
Libraries/TestingServices/Scheduling/TaskAwareBugFindingScheduler.cs

Refactored P#-specific exceptions:
- Removed the previous `PSharpException` (I did not like the previous name because the namespace `Microsoft.PSharp` implied that its a P# exception).
- Introduced the new `Microsoft.PSharp.RuntimeException`, which is the base exception for P# runtime-related exceptions. The user should never catch these exceptions (future TODO).
- Introduced the new `Microsoft.PSharp.ExecutionCanceledException`, which is thrown when the P# runtime/scheduler decides to cancel the execution of a P# machine. This is now thrown instead of `OperationCanceledException` to make it clear that the exception was thrown by P# (and not by user code).
- Introduced the new `Microsoft.PSharp.LoggingException` which replaces the `Microsoft.PSharp.PSharpIOException` (name was weird …

updated P#-specific exceptions

---

Libraries/Core/Runtime/Runtime.cs
Libraries/TestingServices/Engines/BugFindingEngine.cs
Libraries/TestingServices/Engines/ReplayEngine.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Libraries/TestingServices/Scheduling/BugFindingScheduler.cs

Using a `TaskCompletionSource` inside the bug-finding scheduler to wait for the serialized execution to finish when calling `Wait` from the bug-finding runtime. Also did various other minor improvements.

Improved runtime wait during bug-finding mode

---

Libraries/Core/Core.csproj
Libraries/Core/Runtime/PSharpRuntime.cs
Libraries/Core/Runtime/StateMachineRuntime.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Unit/Logging/Correct/CustomLoggerTest.cs

`PSharpRuntime` is now an abstract class. Internally, `StateMachineRuntime` and `BugFindingRuntime` inherit this abstract class and implement its methods accordingly. `PSharpRuntime` also provides basic functionality shared by all runtimes (e.g. logging).
This refactoring aims to ease the introduction of new runtimes.
The cool thing is that there are no changes required from a user's point of view. `PSharpRuntime` is the only publicly exposed runtime (and the user creates one exactly as before, using the factory method `PSharpRuntime.Create`).

Refactoring to abstract runtime

---

Libraries/Core/Library/Machine.cs
Libraries/Core/Runtime/PSharpRuntime.cs
Libraries/Core/Runtime/StateMachineRuntime.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Performance/Tests/CreateMachinesTest.cs
Tests/Core.Tests.Performance/Tests/MailboxTest.cs

New APIs for synchronous (when available) delivery of messages and machine creation.
TODO: Fail if such synchronous execution calls a Receive. Lets create an issue to track this once we merge.

Send and execute event

---

Libraries/Core/Library/Machine.cs
Libraries/Core/Runtime/PSharpRuntime.cs
Libraries/Core/Runtime/StateMachineRuntime.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Performance/Tests/CreateMachinesTest.cs
Tests/Core.Tests.Performance/Tests/MailboxTest.cs
Tests/Core.Tests.Unit/Integration/NoMemoryLeakAfterHaltTest.cs
Tests/Core.Tests.Unit/Integration/NoMemoryLeakInEventSendingTest.cs

- Replaced `runtime.Wait()` with `runtime.Stop()`
- `runtime.Wait()` is still available inside the bug-finding runtime (and is used internally during testing)
- updated integration and performance tests that were using the old `runtime.Wait()`

Replaced runtime.Wait() with runtime.Stop()

---

Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Libraries/TestingServices/Runtime/TestHarnessMachine.cs
Tests/TestingServices.Tests.Unit/BaseTest.cs
Tests/TestingServices.Tests.Unit/EntryPoint/EntryPointThrowExceptionTest.cs
Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj

The bug-finding runtime now catches and reports exceptions thrown in a test entry point method. Also added a unit test.

Support reporting exceptions thrown in test entry point method method

---

Libraries/Core/Library/Machine.cs
Libraries/Core/Runtime/StateMachineRuntime.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest1.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest2.cs
Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj

Now it does sync execution only for the first event. I think this matches more closely with the user expectation. The machine doing SendAndExecute will not block (if the target is available) but it will still spawn a task to handle the rest of the events in the target machine. I don't think this is easy to optimize.

Revised SendAndExecute semantics 

---

Libraries/Core/Configuration/Configuration.cs
Libraries/TestingServices/Engines/AbstractTestingEngine.cs
Libraries/TestingServices/Engines/BugFindingEngine.cs
Libraries/TestingServices/Engines/ReplayEngine.cs
Libraries/TestingServices/SchedulingStrategies/Special/ReplayStrategy.cs
Libraries/TestingServices/Tracing/Schedules/ScheduleTrace.cs
Tests/SharedObjects.Tests.Unit/BaseTest.cs
Tests/TestingServices.Tests.Integration/BaseTest.cs
Tests/TestingServices.Tests.Unit/BaseTest.cs
Tests/TestingServices.Tests.Unit/EntryPoint/EntryPointThrowExceptionTest.cs
Tools/Testing/Replayer/ReplayingProcess.cs
Tools/Testing/Replayer/Utilities/ReplayerCommandLineOptions.cs
Tools/Testing/Tester/Scheduling/TestingProcessScheduler.cs
Tools/Testing/Tester/Testing/TestingProcess.cs
Tools/Testing/Tester/Utilities/TesterCommandLineOptions.cs

All unit tests for bug-finding that contain an injected bug, will now try to replay the bug and assert that the replayer can indeed successfully replay this bug. The only exception is state-caching/cycle-replay unit tests which have this additional assertions disabled (until we fix #89).
This should give us confidence that changes we make do not break the schedule replay engine of P#.

Extended unit tests to check for schedule replay

---

Libraries/Core/Library/Machine.cs
Libraries/Core/Library/Monitor.cs
Tests/TestingServices.Tests.Unit/Machines/Declarations/AmbiguousEventHandlerTest.cs
Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj

`Machine` and `Monitor` could throw an `AmbiguousMatchException` when using reflection to get the event handler to invoke if there were multiple event handler actions with the same name. This fixes this issue.
Also added two unit tests for this.

Fix for AmbiguousMatchException in event handler invocation

---

Libraries/Core/Core.csproj
Libraries/Core/Library/MachineInfo.cs
Libraries/Core/Scheduling/ISchedulable.cs
Libraries/Core/Scheduling/OperationType.cs
Libraries/TestingServices/Engines/BugFindingEngine.cs
Libraries/TestingServices/Liveness/LivenessChecker.cs
Libraries/TestingServices/Runtime/AsynchronousTaskScheduler.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Libraries/TestingServices/Scheduling/BugFindingScheduler.cs
Libraries/TestingServices/SchedulingStrategies/DFS/DFSStrategy.cs
Libraries/TestingServices/SchedulingStrategies/DFS/IterativeDeepeningDFSStrategy.cs
Libraries/TestingServices/SchedulingStrategies/DelayBounded/DelayBoundingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/DelayBounded/ExhaustiveDelayBoundingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/DelayBounded/RandomDelayBoundingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Fuzzing/ProbabilisticRandomStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Fuzzing/RandomStrategy.cs
Libraries/TestingServices/SchedulingStrategies/ISchedulingStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Prioritized/PCTStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/ComboStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/InteractiveStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/MaceMCStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/ReplayStrategy.cs
Libraries/TestingServices/StateCaching/State.cs
Libraries/TestingServices/StateCaching/StateCache.cs
Libraries/TestingServices/Tracing/Machines/MachineActionInfo.cs
Libraries/TestingServices/Tracing/Machines/MachineActionTrace.cs
Libraries/TestingServices/Tracing/Schedules/ScheduleStep.cs
Libraries/TestingServices/Tracing/Schedules/ScheduleTrace.cs
Tests/TestingServices.Tests.Unit/EventHandling/ReceiveEvent/ReceiveEventFailTest.cs

All scheduling strategies now use the new `ISchedulable` interface rather than `MachineInfo` (which implements `ISchedulable`). This change is towards making the scheduling strategies agnostic of P# and thus reusable by arbitrary systematic testing tools that take a dependency.
This also addresses #195.

Refactored scheduling strategies to use the ISchedulable interface

---

Libraries/Core/Configuration/Configuration.cs
Libraries/Core/Utilities/RandomNumberGenerators/DefaultRandomNumberGenerator.cs
Libraries/Core/Utilities/RandomNumberGenerators/IRandomNumberGenerator.cs
Libraries/TestingServices/Runtime/BugFindingRuntime.cs
Libraries/TestingServices/SchedulingStrategies/Fuzzing/ProbabilisticRandomStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Fuzzing/RandomStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Prioritized/PCTStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/ComboStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/MaceMCStrategy.cs
Libraries/TestingServices/SchedulingStrategies/Special/ReplayStrategy.cs
Tests/TestingServices.Tests.Integration/Advanced/ChainReplicationTest.cs
Tests/TestingServices.Tests.Integration/Advanced/FailureDetectorTest.cs
Tests/TestingServices.Tests.Integration/Advanced/RaftTest.cs
Tests/TestingServices.Tests.Integration/BaseTest.cs
Tests/TestingServices.Tests.Unit/EventHandling/MaxInstances1FailTest.cs

Also updated 3 unit tests that were using a fixed seed, since that changed.

Instrumenting scheduling points now happens before create and send

---

Source/Core/Library/Events/EventInfo.cs
Source/Core/Library/Machine.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/SchedulingStrategies/ISchedulable.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs
Source/TestingServices/Scheduling/SchedulableInfo.cs
Tests/TestingServices.Tests.Unit/Features/OperationGroupingTest.cs

Operations can now be grouped (this is based on the previous "operation bounding" implementation).
- `SchedulableInfo` and `EventInfo` now expose a `NextOperationGroupId` which can be used for grouping _events_/_operations_ in a chain (e.g. initialization, failure injection).
- A new operation group can start using the optional parameter `isStarter` from `Runtime.SendEvent(...)`. 
- `ISchedulable` exposes `NextOperationGroupId`, which we can use to further reduce the schedule space with DPOR.

Operation grouping

---

Source/Core/Library/Machine.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs
Source/TestingServices/Statistics/Coverage/CodeCoverageReporter.cs

Introduces API `Monitor(Type T, ...)` in addition to `Monitor<T>(...)`.
Make `CodeCoverageReporter` public.

Changes required for PTester

---

Source/Core/Library/Machine.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Unit/Core.Tests.Unit.csproj
Tests/Core.Tests.Unit/Features/GetOperationGroupIdTest.cs
Tests/Core.Tests.Unit/Features/OperationGroupingTest.cs
Tests/LanguageServices.Tests.Unit/LanguageServices.Tests.Unit.csproj
Tests/SharedObjects.Tests.Unit/SharedObjects.Tests.Unit.csproj
Tests/StaticAnalysis.Tests.Unit/StaticAnalysis.Tests.Unit.csproj
Tests/TestingServices.Tests.Integration/TestingServices.Tests.Integration.csproj
Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj

I changed the `CreateMachine` API to mirror `Send`.  `Runtime.CreateMachine` can now take an optional `OperationGroupId` parameter. 
The `OperationGroupId` are also propagated by the production runtime.
Added unit tests.

OperationGroupId in production

---

Samples/PingPong/PingPong.PSharpLanguage.AsyncAwait/Server.psharp
Source/Core/Library/CachedAction.cs
Source/Core/Library/Machine.cs
Source/Core/Runtime/Exceptions/MachineActionExceptionFilterException.cs
Source/Core/Runtime/PSharpRuntime.cs
Tests/Core.Tests.Unit/ExceptionPropagation/ExceptionPropagationTest.cs

Convert MethodInfo to delegates and add 'when' exception filter for synchronous machine actions

Exception capture for Machine.ExecuteAction sync path

---

Source/Core/Configuration/Configuration.cs
Tools/Compilation/SyntaxRewriter/PSharp.targets
Tools/Compilation/SyntaxRewriter/PSharp.vs2017.targets
Tools/Compilation/SyntaxRewriter/Program.cs
Tools/Testing/Tester/Instrumentation/CodeCoverageInstrumentation.cs

- #236: make MSBuild Rewriter task CSharpVersion use LangVersion
- #241: allow env vars to override app settings for VS coverage tools path

Resolve #236 and #241

---

Source/Core/Runtime/PSharpRuntime.cs

I made this change so that the Replayer breaks at the site of the exception. This does not matter so much to users that use the P# nuget because they will get an "exception unhandled in user code" break at the right point. But when taking a dependence on P# sources, the Replayer breaks at a point when the stack has unwound already. This change follows the same OnFailure logic that we followed for creating dumps at the site of the exception.

Break on failure, for PSharpReplayer

---

Source/Core/IO/Logging/DisposingLogger.cs
Source/Core/IO/Logging/ILogger.cs
Source/Core/IO/Logging/StateMachineLogger.cs
Source/Core/Library/Machine.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs

@pdeligia @TedHartMS What do you guys think of this generalization?
```
/// <param name="inboxSize">Approximate size of the machine's inbox</param>
public virtual void OnHalt(MachineId machineId, int inboxSize)
```
I think it'll be useful to know if a machine's inbox was non-empty when the machine halted. But note that the `inboxSize` is only approximate for production runs because an enqueue can happen after the call to `OnHalt`.

Generalize OnHalt to record events dropped on halt

---

Tools/Testing/Tester/Monitoring/CodeCoverageMonitor.cs
Tools/Testing/Tester/Scheduling/TestingProcessScheduler.cs

When `PSharpTester` is run without /parallel, the instrumented binary is pulled into the `PSharpTester` process; therefore calling `VSPerfCmd /shutdown` from `PSharpTester` can't wait for all instrumented processes to stop, but not waiting means there is some time after `PSharpTester` exits that `VSPerfCmd /shutdown` is still active, and this interferes with a subsequent `PSharpTester` run with no delay. Changed to execute the parallel code path (out of process) if `Configuration.ReportCodeCoverage` is set.

Resolve #254: Make code coverage always run out of process

---

Source/Core/Library/Machine.cs

Machine.Inbox is a List<EventInfo> at present. This pull request proposes using a LinkedList<EventInfo> to implement it. 
Using a linked list gets us O(1) on dequeue operations instead of the O(n) incurred currently owing to the calls to List::RemoveAt in Machine::TryDequeueEvent. O(n) dequeue causes a P# machine to perform badly in situations where its inbox can contain tens of thousands of messages. The performance can degrade completely if the inbox ends up queueing millions/tens of millions of messages (For example, run the Mailbox benchmark in the performance branch - the results are in the attached excel file).
The add operation in Enqueue remains O(1). 
[PerfResults.xlsx](https://github.com/p-org/PSharp/files/1301853/PerfResults.xlsx)

LinkedList for Machine.Inbox to get O(1) dequeue

---

Source/Core/IO/Logging/DisposingLogger.cs
Source/Core/IO/Logging/ILogger.cs
Source/Core/IO/Logging/StateMachineLogger.cs
Source/Core/Library/Machine.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Performance/Tests/LoggerTest.cs

ILogger::OnSend and ILogger::OnEnqueue should not track the current state of the machine that is receiving the message, since access to Machine.CurrentState of the receiver by the sender and the receiver can race.
The current implementations of ILogger are race-y, and can cause null pointer access exceptions.
The pull request includes a (performance) test that manifested these issues. I had originally written it for some other stuff I'm working on - it will be made more complete later.

Fix race conditions in logging

---

Source/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Unit/Logging/CustomLoggerTest.cs
Tests/TestingServices.Tests.Unit/Machines/Statements/PopTest.cs
Tests/TestingServices.Tests.Unit/Machines/Transitions/GotoTransitions/GotoStateMultipleInActionFailTest.cs

This detects some obvious assertions in the code where one machine ends up calling a P# machine on another machine. This will never happen unless a machine reference is passed around.

Additional assertions to make sure a machine reference isn't passed around

---

Source/Core/IO/Logging/DisposingLogger.cs
Source/Core/IO/Logging/ILogger.cs
Source/Core/IO/Logging/StateMachineLogger.cs
Source/Core/Library/Machine.cs

Added a `OnGoto` method to the `ILogger` interface. It is called when a machine invokes `this.Goto` or if a `GotoTransition` fires. The `StateMachineLogger` prints the following:
```
<GotoLog> Machine 'TestLogging.M(0)' is transitioning from state 'TestLogging.M.S1' to state 'TestLogging.M.S2'.
```

Additional OnGoto logging

---

Source/Core/IO/Logging/StateMachineLogger.cs
Source/Core/Library/Events/EventInfo.cs
Source/Core/Library/Machine.cs
Source/Core/Library/SendOptions.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Unit/Logging/CustomLoggerTest.cs
Tests/TestingServices.Tests.Unit/BaseTest.cs
Tests/TestingServices.Tests.Unit/Features/MustHandleEventTest.cs

Changed `Send` to take an optional `options` parameter. Added support for `MustHandle` events, which must be dequeued before the target machine halts.

SendOptions and MustHandle

---

Tests/Core.Tests.Unit/Core.Tests.Unit.csproj
Tests/Core.Tests.Unit/Features/GetOperationGroupIdTest.cs
Tests/Core.Tests.Unit/Features/OnHaltTest.cs
Tests/Core.Tests.Unit/Features/OperationGroupingTest.cs
Tests/LanguageServices.Tests.Unit/LanguageServices.Tests.Unit.csproj
Tests/SharedObjects.Tests.Unit/SharedObjects.Tests.Unit.csproj
Tests/StaticAnalysis.Tests.Unit/StaticAnalysis.Tests.Unit.csproj
Tests/TestingServices.Tests.Integration/TestingServices.Tests.Integration.csproj
Tests/TestingServices.Tests.Unit/Machines/Declarations/NameofTest.cs
Tests/TestingServices.Tests.Unit/Machines/Transitions/GotoTransitions/GotoStateTest.cs
Tests/TestingServices.Tests.Unit/TestingServices.Tests.Unit.csproj
Tests/run-integration-tests.ps1
Tests/run-unit-tests.ps1

Unit tests may no longer be discovered after this. If you encounter that, remove folder %TEMP%\VisualStudioTestExplorerExtensions and restart VS. This still didn't work for me until I created and ran a simple Xunit UT project following https://xunit.github.io/docs/getting-started-desktop.html (which re-creates this directory) and restarted VS. Also, CodeLens sometimes wasn't showing the status/run icon for UTs; that seems to work now.

Update to Xunit2.3.1 (necessary for VS 2017 Update 4.x)

---

Source/AddOns/DynamicRaceDetection/ThreadMonitor/Monitoring/Threads/ThreadExecutionMonitorDispatcher.cs
Source/AddOns/DynamicRaceDetection/ThreadMonitor/Utilities/ThreadMonitorCommandLineOptions.cs
Source/TestingServices/RaceDetection/RaceDetectionEngine.cs

Modifications:
1. /replay:file_name> will now set EnableReadWriteTracing falg as true, to include tracing during replay.
2. GetDebugInformation goes through the call stack till it reaches Machine.cs code file. (Maximum upto 15).
3. Removed unwanted diagnostic string.

StackTrace in race report during replay.

---

Source/Core/Library/Machine.cs
Tests/TestingServices.Tests.Unit/Features/OnExceptionTest.cs

Added a method `OnException` to the `Machine` class. This method is called (in a `when` clause) when there is an unhandled exception thrown by a handler. The user can handle such exceptions in one place (instead of adding a try-catch to each handler).

On exception

---

Source/Core/Library/Machine.cs
Source/Core/Runtime/PSharpRuntime.cs
Source/Core/Runtime/StateMachineRuntime.cs
Source/TestingServices/Events/QuiescentEvent.cs
Source/TestingServices/Runtime/BugFindingRuntime.cs
Tests/Core.Tests.Unit/RuntimeInterface/SendAndExecuteTest3.cs
Tests/Core.Tests.Unit/RuntimeInterface/SendAndExecuteTest4.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest1.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest3.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest4.cs

The methods `CreateMachineAndExecute` and `SendEventAndExecute` when executed, if the target machine was idle, then these methods block until it becomes idle again. If the target machine wasn't idle at the time of the call, then the methods return immediately. This matches with a _RunToCompletion_ semantics for scheduling. 
Unlike previous implementation of these methods (which was only for optimization), the user can now rely on the semantics to control scheduling.

Revised sync execution semantics to match RunToCompletion

---

Tools/Compilation/SyntaxRewriter/Program.cs

Modifying SyntaxRewriter to allow psharp targets to be included for projects without any .psharp files - the rewriter will simply ignore such projects.

Fixing build failure when psharp targets are included without .psharp files

---

Source/Core/Library/Machine.cs
Source/Core/Library/UnHandledEventException.cs
Source/Core/Runtime/Exceptions/OnExceptionOutcome.cs
Tests/Core.Tests.Unit/ExceptionPropagation/OnExceptionTest.cs
Tests/Core.Tests.Unit/RuntimeInterface/SendAndExecuteTest6.cs
Tests/TestingServices.Tests.Unit/Features/OnExceptionTest.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest6.cs

The OnException can now request for the machine to be gracefully halted (as an alternative to crashing the runtime).
Further, an UnHandled event now goes through OnException (which can choose to halt the machine).

Halt on unhandled exception

---

Source/TestingServices/Engines/BugFindingEngine.cs
Source/TestingServices/Engines/ReplayEngine.cs

It was trying to display the log before checking for liveness/races.

Fixed error console log not properly displaying in some corner cases

---

Source/AddOns/ServiceFabric/Runtime/OutboxEvent.cs
Source/AddOns/ServiceFabric/Runtime/PSharpService.cs
Source/AddOns/ServiceFabric/Runtime/StateMachineRuntime.cs
Source/AddOns/ServiceFabric/Runtime/StateManagerExtensions.cs

Implements one outbox queue per machine. 
When a machine is created, a `ClearMachineOutbox` task is created to constantly empty its outbox.
When a machine halts, its outbox is marked for deletion (necessary in case of failure right after the machine halts). The `ClearMachineOutbox` task checks if the machine has been halted. If so, it tries to empty the queue one last time. When the outbox is empty, it deletes the  outbox and unmarks for deletion. 
On rehydration, we create the`ClearMachineOutbox` task for each outbox marked for deletion (these are the machines that were halted before failure but their outbox wasn't completely emptied).

Outbox per machine

---

Scripts/NuGet/PSharp.nuspec
Tools/Testing/Tester/Interfaces/ITestingProcess.cs
Tools/Testing/Tester/Interfaces/ITestingProcessScheduler.cs
Tools/Testing/Tester/Interfaces/KnownTypesProvider.cs
Tools/Testing/Tester/Scheduling/TestingProcessScheduler.cs
Tools/Testing/Tester/Tester.csproj
Tools/Testing/Tester/Testing/TestingProcess.cs

Fixes packaging of .NET Core in NuGet. Also removes dependency of `System.ServiceModel` in .NET Core version of `PSharpTester`. This fix will also result into a smaller size NuGet package!

Fixes in nuspec and removed dependency in P# tester for .NET core

---

Source/TestingServices/Engines/AbstractTestingEngine.cs

There was a bug (recently introduced) in the tester, where it would try to access the `ErrorReporter` (when unable to load an assembly), but the `ErrorReporter` is not initialized yet.
This change makes sure stuff are initialized first, before being accessed.

Fix in tester internal exception when not able to load assembly

---

Scripts/NuGet/PSharp.nuspec
Scripts/create-nuget-package.ps1

Changeset:
- The property `requireLicenseAcceptance` in the NuGet spec is now true.
- The NuGet package is now placed under `bin\nuget`.

Updates for building the NuGet package

---

Source/Core/Utilities/Tooling/BaseCommandLineOptions.cs
Tools/Compilation/Compiler/Utilities/CompilerCommandLineOptions.cs
Tools/Testing/Replayer/Utilities/ReplayerCommandLineOptions.cs
Tools/Testing/Tester/Utilities/TesterCommandLineOptions.cs

Someone can now do either (for example) `/i:10` or `-i:10`. By default, the tool instructions now suggest to use `-`. This affects the tester, replayer and compiler.

using regex to support multiple command line option prefixes

---

Common/version.props
Scripts/NuGet/PSharp.nuspec
Source/Core/Configuration.cs
Source/TestingServices/Runtime/TestingRuntime.cs
Tests/TestingServices.Tests.Unit/RuntimeInterface/SendAndExecuteTest8.cs
Tools/Visualization/TraceViewer/Properties/AssemblyInfo.cs

Disabled the assert that P# APi cannot be called after an raise/goto/pop/push, when sending the quiesce event. That is not applicable because the event handler has necessarily finished by then.

Disabled assert on sending QuisceEvent

---

Source/TestingServices/Runtime/TestingRuntime.cs

A machine transitions to the null state for a brief time before it fails or halts.

Defend against potential null-deref in coverage reporting 

---

Source/TestingServices/Engines/BugFindingEngine.cs
Source/TestingServices/Statistics/TestReport.cs
Tools/Testing/Tester/Program.cs
Tools/Testing/Tester/Scheduling/TestingProcessScheduler.cs
Tools/Testing/Tester/Testing/TestingProcess.cs
Tools/Testing/Tester/Utilities/ExitCode.cs

The exit codes are:
`0` for success (no bugs found)
`1` for bug(s) found
`2` for internal error
Also fixed a bit the behavior of when an internal error occurs. Now internal errors are captured as strings in the test report, and the tester does not crash, instead tries to exit gracefully.

added exit codes for the tester

---

Docs/README.md
Docs/Testing/TestingMethodology.md
Docs/Testing/UnitTesting.md
README.md
Source/Core/IO/Logging/MachineLogger.cs
Source/Core/Runtime/BaseRuntime.cs
Source/Core/Runtime/EventQueues/EventQueue.cs
Source/TestingServices/Runtime/EventQueues/MockEventQueue.cs
Source/TestingServices/Runtime/Machines/MachineTestKit.cs
Source/TestingServices/Runtime/Machines/MachineTestingRuntime.cs
Source/TestingServices/Runtime/TestingRuntime.cs
Tests/Core.Tests/Core.Tests.csproj
Tests/Core.Tests/Machines/GotoStateTransitionTest.cs
Tests/Core.Tests/Machines/HandleEventTest.cs
Tests/Core.Tests/Machines/InvokeMethodTest.cs
Tests/Core.Tests/Machines/ReceiveEventIntegrationTest.cs
Tests/Core.Tests/Machines/ReceiveEventStressTest.cs
Tests/Core.Tests/Machines/ReceiveEventTest.cs

Our current testing APIs (i.e. `BugFindingEngine` and P# tester) allows someone to write powerful _integration-tests_, which can serialize a P# program, and systematically test _end-to-end_ a collection of P# machines, as well as the concurrency between machines. However, we do not support a proper way of testing production machines, especially in isolation in a true _unit-testing_ fashion. All our tests under `Core.Tests` today are integration tests for production, where we nondeterministically run machines waiting for a task completion source, to assert that the execution completed
This PR introduces `MachineTestKit`, which allows us (and P# clients) to write true unit-tests, i.e. execute machines sequentially (in relation to the test method), manually send events every time machine …

New test APIs for unit-testing machines in isolation

---

Source/Core/Runtime/EventHandlers/EventHandlerStatus.cs
Source/Core/Runtime/Machines/Machine.cs
Tests/TestingServices.Tests/Runtime/OnEventDequeueOrHandledTest.cs

Exceptions thrown in Machine callbacks OnEventDequeueAsync and OnEventHandledAsync go through OnException (so they can be handled like other exceptions thrown by machines).

Exceptions in Machine callbacks

---

Source/Core/Runtime/Machines/MachineFactory.cs
Source/TestingServices/Runtime/SystematicTestingRuntime.cs
Source/TestingServices/Statistics/Coverage/CoverageInfo.cs
Tests/TestingServices.Tests/Coverage/ActivityCoverageTest.cs

Fix coverage reporting across multiple invocations of the testing engine. Added a test case to capture future regressions.

Coverage reporting with multiple tests

---

Source/LanguageServices/Parsing/Visitors/Syntax/Declarations/EventDeclarationVisitor.cs
Source/LanguageServices/Syntax/Declarations/EventDeclaration.cs
Tests/LanguageServices.Tests/Declarations/EventInheritanceTests.cs
Tests/LanguageServices.Tests/Declarations/EventTests.cs

Also, fixed error with insertion of call to SetCardinalityConstraints in the generated code.

Removed assert/assume parsing from psharp syntax. 

---

Source/Core/Runtime/EventHandlers/EventHandlerStatus.cs
Source/Core/Runtime/Machines/Machine.cs
Tests/TestingServices.Tests/Runtime/OnEventUnhandledTest.cs

Added a Machine callback OnEventUnhandledAsync that is invoked when the machine dequeues an event that cannot be handled by it.

OnEventHandledAsync

---

Tests/TestingServices.Tests/Runtime/MustHandleEventTest.cs
Tools/VisualStudio/VisualStudio/BraceMatching/BraceMatchingTagger.cs
Tools/VisualStudio/VisualStudio/Classification/ClassificationFormats.cs

Fix brace matching at end of file specifically. Also switched to using standard colors so that the "light" theme looks nice.
Currently the P# language service defined custom colors with hard coded defaults that are not sensitive to the theme. The colors chosen look good on dark theme but not the light theme. These colors show up here in the Environment/Fonts and colors dialog so user can change them.
But is it important for users to be able to change the colors for P# tokens specifically? The downside with hard coded colors is that they look washed out when you switch to the light theme. Here the P# colors do not match C# code, they look washed out:
This is because our colors are not "theme sensitive". But if we switch to using standard colors then the light and dark themes work equally …

fix bug in brace matching and colors

---

Scripts/build.ps1

this is so that the CI build fails instead of passes in this case.

fix error code from dotnet core sdk check
